# Generated by Django 4.1.7 on 2023-03-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "main",
            "0001_squashed_0002_alter_ingredient_amount_alter_ingredient_brand_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
