# Generated by Django 4.1.7 on 2023-04-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_ingredient_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="note",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
