# Generated by Django 4.1.7 on 2023-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_ingredient_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="note",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
