# Generated by Django 4.1.5 on 2023-02-06 18:35

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_time_timecategory_time_time_category_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("name", "user"),
                name="recipes_tag_unique_name_user",
            ),
        ),
    ]
