# Generated by Django 4.1.6 on 2023-02-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_recipe_servings"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
