# Generated by Django 4.1.7 on 2023-03-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0013_ingredient_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingredients",
                to="recipes.unit",
            ),
        ),
    ]
