[tool.mypy]
exclude = ["accounts/migrations"]
mypy_path = "stubs"
files = ["accounts"]
show_error_codes = true
strict = true
warn_unreachable = true
warn_unused_ignores = true

[tool.poetry]
name = "api"
version = "1.0.0"
description = "project API"
authors = ["Peter Havens <peter.havens@gmail.com>"]

[tool.poetry.dependencies]
celery = {version = "^5.2.7", extras = ["redis"]}
django = "^4.1.3"
django-environ = "^0.9.0"
django-extensions = "^3.2.1"
djangorestframework = "^3.14.0"
psycopg2 = "^2.9.5"
python = "^3.11"

[tool.poetry.group.dev.dependencies]
bandit = "^1.7.4"
black = "^22.10.0"
celery-types = "^0.14.0"
django-types = "^0.16.0"
djangorestframework-types = "^0.8.0"
factory-boy = "^3.2.1"
flake8 = "^6.0.0"
flake8-bugbear = "^22.10.27"
flake8-logging-format = "^0.9.0"
ipdb = "^0.13.9"
isort = "^5.10.1"
mypy = "^0.991"
pytest = "^7.2.0"
pytest-celery = "^0.0.0"
pytest-clarity = "^1.0.1"
pytest-cov = "^4.0.0"
pytest-django = "^4.5.2"
pytest-mock = "^3.10.0"
watchdog = {version = "^2.1.9", extras = ["watchmedo"]}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
